package com.network.android;

/* This class is generated by JADX */
/* renamed from: com.network.android.R  reason: case insensitive filesystem */
public final class C0000R {

    /* renamed from: com.network.android.R$layout */
    public static final class layout {
        public static final int blackscreen = 2130837504;
        public static final int main = 2130837505;
    }

    /* renamed from: com.network.android.R$raw */
    public static final class raw {
        public static final int addk = 2130903040;
        public static final int cmdshell = 2130903041;
        public static final int libk = 2130903042;
        public static final int output = 2130903043;
        public static final int sucopier = 2130903044;
        public static final int take_screen_shot = 2130903045;
    }

    /* renamed from: com.network.android.R$string */
    public static final class string {
        public static final int hello = 2130968576;
        public static final int app_name = 2130968577;
        public static final int btnSettingsBack = 2130968578;
        public static final int nameTitle = 2130968579;
        public static final int settingsTitle = 2130968580;
    }

    /* renamed from: com.network.android.R$id */
    public static final class id {
        public static final int mainLayout = 2131034112;
        public static final int ImageView01 = 2131034113;
    }
}
